### ISSUE TITLE
Search input broken

### ISSUE THREAD

**Issue by cbroberg** [SKempin/reactjs-tmdb-app#4]
Looks nice. Keyboard doesn't pop up in search on iPhone 6S. Checking Mac browser tomorrow. 

Same problem with entering search on the web through Safari. You have to hold the mouse in the field to enter a search term. It only works in Google Chrome. But here it is lightning fast. Looking forward to a fix ;)

**Comment by SKempin** [comment]
Attaching screenshots of this issue. On iOS you have to click the bottom left toolbar upwards arrow in order to select the input area.

Bottom toolbar appears on initial input box click:
![1](https://cloud.githubusercontent.com/assets/10877466/23299487/a7a5507e-fa79-11e6-93ca-248e05ae4d53.PNG)

Tapping on the bottom left arrow in the toolbar then allows input in the input area:
![2](https://cloud.githubusercontent.com/assets/10877466/23299486/a7a570e0-fa79-11e6-92ad-6d526bb66910.PNG)

**Comment by siimonevans** [comment]
The problem lies with how your elements have been nested/positioned. The current markup displays a label, followed by a span element that finally contains the input field - [screenshot here](http://imgur.com/a/y0bsK) to reference. On mobile, it seems like you're tapping the input field when really the label is what's in the way.

As a quick test/proof of issue, removing the label tag and just having `form` > `span` > `input` solves your problem. Obviously, you should keep the label for accessibility reasons, but right now it's occupying the space _in front_ of the input and therefore preventing the keyboard from popping up.

Markup refactoring is required, or maybe a `z-index` fix.

EDIT: I imagine the toolbar is appearing since there are multiple form elements to cycle through within the form.

**Comment by SKempin** [comment]
@SimonDEvans On that last note, I'm slightly confused on why there are two input elements appearing in the search? Do you know what is causing this? Thanks again.

<img width="750" alt="screen shot 2017-02-25 at 20 52 20" src="https://cloud.githubusercontent.com/assets/10877466/23334705/75fedeb8-fb9c-11e6-9345-f7e6620d665d.png">

**Comment by siimonevans** [comment]
@SKempin the duplication appears to be caused by the typeahead.js plugin.

**Comment by mesqueeb** [comment]
I have the same issue. Will it be fixed soon?

**Comment by SKempin** [comment]
@mesqueeb This is caused by interaction with the label component, but removing this causes accessibility issues. Happy to discuss if you would like to look at address this with me?

**Comment by DanWilkes02** [comment]
Hi I know this is an older issue but is it fixed? I'm trying to get more frontend experience and I'll fork the repo and take a look if you want.

**Comment by SKempin** [comment]
@DanWilkes02 This issue still persists, however I have commented out the label in the repo as a temporary fix. You can checkout an old commit if you would like to take a look, which would be much appreciated. 

The label was commented out on commit `246ed37e2e2ece1d102f3be4f3f16bc99b49fde2`

**Comment by SKempin** [comment]
@DanWilkes02 Just wondering if you are looking at this? Thanks.

**Comment by DanWilkes02** [comment]
I'm so sorry I've been super busy (ugh exams!) and this completely slipped my mind.
